### ISSUE TITLE
support for gDrive and others cloud storage services

### ISSUE THREAD

**Issue by emilwojcik93** [AudDMusic/RedditBot#10]
Hello,
Could you please add support for gDrive and others cloud storage services (MS Azure, Apple iCloud, Mega NZ, Dropbox).

[example reddit comment with gDrive URL](https://www.reddit.com/r/starcitizen/comments/sxz4ig/comment/hxyfae3/?utm_source=share&utm_medium=web2x&context=3)

Thank you and best regards,
emilwojcik93

**Comment by Mihonarium** [comment]
If a Google Drive URL leads to a folder, it’s not apparent what the bot behaviour should be. The bot is for identifying music posted on Reddit; people usually don’t do that via cloud storage services.

But if you can get a direct file URL, you can point the bot to it.
