### ISSUE TITLE
Bot should look for timestamps that start with @ 

### ISSUE THREAD

**Issue by Zomega** [AudDMusic/RedditBot#17]
Example: https://www.reddit.com/r/KnowledgeFight/comments/yybjtw/748_november_16th_2022/iwto3ts?utm_medium=android_app&utm_source=share&context=3

The original commenter gave a time to check, but the bot identified the song at the beginning of the 1.5h audio rather than 45:00 in as requested.

I'll see if I can make a PR, this is a really cool idea for a bot and I appreciate your work!

**Comment by Zomega** [comment]
Ok, reading the code, looks like it's more a problem with the format of this timestamp. I'll see if I can support timestamps with leading @.

**Comment by Mihonarium** [comment]
Thanks for opening the issue! Should work now
