### ISSUE TITLE
Optional AcoustID detection?

### ISSUE THREAD

**Issue by Avamander** [AudDMusic/RedditBot#2]
Would it also be possible to add [AcoustID](https://acoustid.org/)-based detection to the bot, this could increase the likelihood that a match is found, plus optionally the available MusicBrainz links and data from there can be very useful.

**Comment by Mihonarium** [comment]
Thanks for writing this! But nope, AcoustID's database is four times smaller than AudD's and uses Chromaprint, which is especially bad for small or distorted audio fragments. It just won't work for most of the music used on Reddit and is not able to improve the accuracy compared to AudD.

AudD API allows requesting MusicBrainz data, but how would the bot use it?

**Comment by Mihonarium** [comment]
Thanks for writing this! But nope, AcoustID's database is four times smaller than AudD's and uses Chromaprint, which is especially bad for small or distorted audio fragments. It just won't work for most of the music used on Reddit and is not able to improve the accuracy compared to AudD.

AudD API allows requesting MusicBrainz data, but how would the bot use it?

**Comment by Mihonarium** [comment]
Thanks for writing this! But nope, AcoustID's database is four times smaller than AudD's and uses Chromaprint, which is especially bad for small or distorted audio fragments. It just won't work for most of the music used on Reddit and is not able to improve the accuracy compared to AudD.

AudD API allows requesting MusicBrainz data, but how would the bot need it?

(Please open another issue if you think the bot should post more info or something. In that case, I can request more metadata, including the MusicBrainz metadata, from the API. AcoustID doesn't seem relevant)
