### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nicolasmaia** [AudDMusic/RedditBot#5]
Currently this project has no licensing information. I suggest AGPLv3.

**Comment by AudD-music** [comment]
Just in case, there are [MIT licensed examples](https://github.com/AudDMusic/audd-go/tree/master/examples) of interaction with the API, and the bot uses two other open-source libraries for the Reddit API.

Would you mind telling us more about why do you need an open-source license for this code?.

**Comment by nicolasmaia** [comment]
Oh, I just assumed your forgot to add one, since you published the code on Github. I don't have a personal need involved in this request, though.

**Comment by AudD-music** [comment]
Ah, got it. Thanks!

If anyone needs a license, please comment on this issue, we'll consider adding one. Closing for now

**Comment by TheTechRobo** [comment]
https://choosealicense.com/no-permission/

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

Also...

> You don’t have to do anything to not offer a license. You may, however, wish to add a copyright notice and statement that you are not offering any license in a prominent place (e.g., your project’s README) so that users don’t assume you made an oversight. If you’re going to accept others’ contributions to your non-licensed project, you may wish to explore adding a contributor agreement to your project with your lawyer so that you maintain copyright permission from contributors, even though you’re not granting the same.

**Comment by AudD-music** [comment]
Hey @TheTechRobo,

Please let us know if there's a use case for the code or if you want to contribute.
