### ISSUE TITLE
Formatting issues when no date available

### ISSUE THREAD

**Issue by kitchen-ace** [AudDMusic/RedditBot#6]
Hi, auddbot just commented on a post I made. It didn't have the date for one song, and so it just displays two backticks. On old reddit, this looks even worse and breaks the formatting a bit. 

It's on the last track suggested.

Normal post: https://www.reddit.com/r/TIHI/comments/qr3ytx/thanks_i_hate_jelly_hands/hk5fmd0/?context=1

Old reddit: https://old.reddit.com/r/TIHI/comments/qr3ytx/thanks_i_hate_jelly_hands/hk5fmd0/?context=1

**Comment by Mihonarium** [comment]
Thanks! [Fixed](https://github.com/AudDMusic/RedditBot/commit/b90a5cc5ef64eda8c52840da26e33bb4cc279433).
