### ISSUE TITLE
to find the background music

### ISSUE THREAD

**Issue by URMOMMASDOG** [AudDMusic/RedditBot#8]
Hello! i was on a phone call while on hold and i noticed that the hold music was from an online song from youtube called " pua (feat. Offsite & Tango)" By drops of andromeda . i am not able to find the back ground music without the drums and extra additions to the flute, is there a way to help?
Heres a mp3 version if you'd like
https://user-images.githubusercontent.com/97133469/148135479-96f66917-8d34-4161-8f25-0cc782df1fe6.mp4

**Comment by Mihonarium** [comment]
The only match we have in our DB is with [Drops of Andromeda - pua (feat. Offsite & Tango)](https://lis.tn/PuaFeatOffsite%26Tango). If the bot doesn't know something, we can't really help.

I can suggest posting the question on r/WhatsThisSong and/or r/tipofmytongue.
